global:
  storageClass: ""
  redis:
    password: "redisPassword"

# -- master configuration parameters
master:
  count: 1
  persistence:
    size: 4Gi    
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "cloud.google.com/gke-nodepool"
            operator: In
            values:
            - "critical"    

# -- replicas configuration parameters
replica:
  replicaCount: 2
  persistence:
    size: 4Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "cloud.google.com/gke-nodepool"
            operator: In
            values:
            - "critical"    