name: 'Create README.md file'
permissions: write-all

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*README.md'
  workflow_dispatch:

jobs:
  readme-create:
    uses: clouddrove/github-shared-workflows/.github/workflows/readme.yml@master
    secrets:
      TOKEN: ${{ secrets.GITHUB }}
      SLACK_WEBHOOK_TERRAFORM: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }}

  # Create README for each Submodules
  readme-create-addon:
    name: 'Addon readme-create'
    runs-on: ubuntu-latest
    steps:
      - name: Updating GitHub Token
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ env.GH_TOKEN }}

      - name: Generate TF Docs
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: addons/cluster-autoscaler,addons/cert-manager,addons/ingress-nginx,addons/keda,addons/reloader,addons/kubeclarity,addons/external-dns,addons/external-secrets,addons/filebeat,addons/actions-runner-controller,addons/redis,addons/prometheus

          git-push: true
          template: |-
            <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
            {{ .Content }}
            <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
          git-push-user-name: "clouddrove-ci"
          git-push-user-email: 84795582+clouddrove-ci@users.noreply.github.com
          git-commit-message: "readme: Update add-on's readme"

          
